### ISSUE TITLE
RRNet结果百度链接

### ISSUE THREAD

**Issue by Dpw506** [rmcong/RRNet_TGRS2021#1]
您好！https://pan.baidu.com/share/init?surl=Zt6PsB5zAl4Tts_4g7I9OQ，这个百度网盘的链接能打开但是输入提取码，没动静，您能提供一下新的链接吗？

**Comment by rmcong** [comment]
你好，我这里是正常的，你让被人试试吧
-------------------------------------------------------------------------
Best regards,

Runmin Cong
Associate Professor
Beijing Jiaotong University (BJTU), Beijing, China
https://rmcong.github.io/



Dpw506 ***@***.***> 于2022年4月23日周六 13:56写道：

**Comment by Dpw506** [comment]
谢谢您的回复，问题已解决
